### ISSUE TITLE
Library Empty

### ISSUE THREAD

**Issue by LennyPhoenix** [kimtore/pms#139]
Hi, I feel like I might be missing something critical here.

I've just installed pms, and have set up the config file as follows:

```
set center

bind = volume +2
```

When opening pms, it appears my library is empty, although it is connected to mpd quite happily:

![image](https://github.com/kimtore/pms/assets/57148878/895f53d7-7378-404e-81c5-0fe38f353912)

Here is the startup log:

[pms.log](https://github.com/kimtore/pms/files/15192780/pms.log)

**Comment by LennyPhoenix** [comment]
If I queue some tracks using a different client they appear in the queue menu too:

![image](https://github.com/kimtore/pms/assets/57148878/ad378fed-0da3-4736-8f6d-13d437cc698d)

**Comment by kimtore** [comment]
Hi, thanks for using PMS.

I think I found the bug and fixed it, please re-open the issue if this is not the case.

Please also note that depending on the size of your music library, you might have to configure MPD; see [the documentation](https://github.com/kimtore/pms/blob/master/doc/mpd.md).

**Comment by LennyPhoenix** [comment]
![image](https://github.com/kimtore/pms/assets/57148878/908b45e8-db9e-4aea-af33-399e6e21e219)

Seems to be working now, thanks!

**Comment by LennyPhoenix** [comment]
![image](https://github.com/kimtore/pms/assets/57148878/4b715ba7-2ed0-4856-bf5d-978bb60c9be7)
Bug just magically came back, was fine earlier today. Really not sure what the cause is, I've already patched my mpd config to allow for a larger buffer

**Comment by LennyPhoenix** [comment]
Magically fixed on restart :shrug:
